apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-volume-pv
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/data/shared-volume"
