apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: order-consumer-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-consumer-deployment
  minReplicas: 1
  maxReplicas: 5 
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-consumer-deployment
spec:
  selector:
    matchLabels:
      app: order-consumer
  template:
    metadata:
      labels:
        app: order-consumer
    spec:
      containers:
        - name: order-consumer-container
          image: pavan5670/ecommerce-microservice-order-consumer
          ports:
            - containerPort: 3020
          envFrom:
            - secretRef:
                name: secret
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/temp_files
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: order-consumer-service
spec:
  selector:
    app: order-consumer
  ports:
    - protocol: TCP
      port: 3020
      targetPort: 3020
  type: NodePort
